name: Bingo
version: '${project.version}'
main: de.aquafun3d.bingo.Main
api-version: '1.21'
authors: [ AquaFun3D ]
description: Minecraft Bingo Plugin

commands:
  top:
    description: Brings the player to the surface (overworld if in Nether/End)
  teambackpack:
    description: Opens the shared team backpack
    aliases: [tbp, teambp, bp]
  start:
    description: starts the game
  bingo:
    description: shows your Bingo-Items
  settings:
    description: Bingo settings
  spawn:
    description: teleports the player to the spawn
  skip:
    description: skips an item